version: 2.1
jobs:
  helm-package:
    docker:
      - image: 708371444347.dkr.ecr.us-east-1.amazonaws.com/concourse-runner:latest
        aws_auth:
          aws_access_key_id: $OPS_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $OPS_AWS_SECRET_ACCESS_KEY
    environment:
      GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes'
    steps:
      - run:
          name: "clone airbyte-helm repo"
          command: | 
             git clone git@github.com:datacamp-engineering/airbyte-chart-helm.git
      - run:
          name: "helm package airbyte"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add worker-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "commit new version"
          command: |
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             rm -f index.yaml
             helm3 repo index --url https://datacamp-engineering.github.io/airbyte-chart-helm/ .
             git add index.yaml
             git config --global user.email datacamp-circleci-user@users.noreply.github.com
             git commit -m "commit new version 0.33.${CIRCLE_BUILD_NUM} [ci skip]"
             git push -u origin master
workflows:
  version: 2
  build:
    jobs:
      - helm-package:
          context: org-global
          filters:
            branches:
              only: master